#!/bin/bash

#remove any .jpg images already in folder
rm Experiment_Images/*.jpg

dir="Experiment_Images/"
ext=".jpg"

for i in $dir*.pgm
{
	name=${i%.*}
	name="$name$ext"
	convert -resize 100x100 $i $name
} 
